### ISSUE TITLE
Toto mi poslal Bu

### ISSUE THREAD

**Issue by MarrekNozka** [spseol/rozvrh#1]
Jak se obnovují data?
Co když dojde ke změně suplování?
Mě tam visí nějaká suplování v pondělí a včera, která jsem neměl.
http://then0rth.pythonanywhere.com/rozvrh/Burda%20Ji%C5%99%C3%AD

**Comment by then0rTh** [comment]
Změny se obnovují kazdou hodinu, novější změny pro dané datum by měly přepsat ty starší (to je spíš moje domněnka, situaci kdy se změní změny jsem netestoval).

Ohledně pondělí: nastala situace kdy byly vypsány změny na 2 dny současně - s tím jsem nepočítal. Mám připravenou úpravu, co by tuto situaci měla řešit - zbývá jen ji nahrát a čekat, až zase bude dvojité suplování (abych věděl jestli to pomohlo)

**Comment by then0rTh** [comment]
Dnes je suplování na 2 dny a vše se zdá být ok, zavírám.
