### ISSUE TITLE
Změny 2018-12-10

### ISSUE THREAD

**Issue by MarrekNozka** [spseol/rozvrh#2]
## Změny 2018-12-10

1.Hod SIT odpadá 3VT (3VS2) praxe
2.Hod SIT odpadá 3VT (3VS2) praxe
3.Hod DBI odpadá 4L exkurze, výlet
4.Hod EPO supl. (Oš) 3B (3Bb) (JU2)
5.Hod DBI odpadá 4L exkurze, výlet

3.4.5. je v pořádku, ale 1. a 2. se zobrazuje zobrazuje jako by bylo vše beze změn...

**Comment by then0rTh** [comment]
opraveno
