### ISSUE TITLE
nezobrazuje se odpadlá ve zkouškovém

### ISSUE THREAD

**Issue by MarrekNozka** [spseol/rozvrh#3]
Suplování:   Čtvrtek 24.1.2019 

http://then0rth.pythonanywhere.com/rozvrh/No%C5%BEka%20Marek

Druhá hodina mi odpadá, protože je zkouškové, ale v rozvrhu hormálně je....

Marek Nožka

**Comment by then0rTh** [comment]
V rozvrhu máte 3VE ale na změnách 3VT, proto se změna nezobrazila. Trochu jsem uvolnil podmínky, takže už se zobrazuje.

**Comment by MarrekNozka** [comment]
Aha. Toho jsem si ani nevšiml. Je to tím, že je to hodina pro spojené 3VT i 3VE.
